# Generated by Django 6.0.3 on 2026-07-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
