# Generated by Django 6.0.3 on 2026-07-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, default='NEW COLLECTION', max_length=100)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_link', models.CharField(default='/shop', max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('bg_gradient', models.CharField(default='linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Verified Buyer', max_length=100)),
                ('avatar', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('verified_buyer', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flash Sale - Up to 40% Off', max_length=200)),
                ('subtitle', models.CharField(default='Limited time offer on top tech & lifestyle gear', max_length=200)),
                ('discount_percentage', models.PositiveIntegerField(default=30)),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flash_deals', to='store.product')),
            ],
        ),
    ]
